"""Report generation and download section."""

import streamlit as st
import json
from datetime import datetime
from typing import Dict


def generate_report(result: Dict) -> str:
    """Generate a text report from analysis result."""
    abnormalities_text = ""
    if result.get("abnormalities"):
        for i, ab in enumerate(result["abnormalities"]):
            abnormalities_text += (
                f"{i+1}. {ab.get('type', 'Unknown')}: "
                f"{ab.get('description', 'N/A')}\n"
            )
    else:
        abnormalities_text = "No chromosomal abnormalities detected.\n"

    return f"""
CHROMOSOME KARYOTYPE ANALYSIS REPORT
====================================

Analysis Date: {result.get('analysis_time', 'N/A')}
AI Provider: {result.get('provider', 'N/A')}

ISCN 2020 Notation: {result.get('notation', 'N/A')}

SUMMARY
-------
Chromosome Count: {result.get('chromosome_count', 'N/A')}
Sex Chromosomes: {result.get('sex_chromosomes', 'N/A')}
Confidence Score: {result.get('confidence', 0):.1f}%

DETECTED ABNORMALITIES
---------------------
{abnormalities_text}

CLINICAL INTERPRETATION
----------------------
{result.get('interpretation', 'N/A')}

DETAILED FINDINGS
----------------
{result.get('detailed_findings', 'N/A')}

TECHNICAL NOTES
--------------
{result.get('technical_notes', 'N/A')}

DISCLAIMER
----------
This analysis is for educational and research purposes only.
Results must be validated by qualified cytogenetics professionals.

Generated by Chromosome Karyotype Analyzer
"""


def display_report_section(result: Dict):
    """Display the report download section."""
    st.header("📄 Generate Report")
    col1, col2 = st.columns(2)
    with col1:
        st.download_button(
            label="📥 Download Text Report",
            data=generate_report(result),
            file_name=f"karyotype_analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
            mime="text/plain",
        )
    with col2:
        st.download_button(
            label="📥 Download JSON Data",
            data=json.dumps(result, indent=2, ensure_ascii=False),
            file_name=f"karyotype_analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json",
            mime="application/json",
        )
